run:
  deadline: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs-use-default: true
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
    - ".*\\.validator\\.pb\\.go$"
  modules-download-mode: readonly
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - revive
    - gofmt
    - ineffassign
    - staticcheck
    - typecheck
    - gocyclo
    - goconst
    - misspell
    - lll
    - nakedret
    - prealloc
    - gosec
    - bodyclose
    - stylecheck
    - unparam
    - durationcheck
    - unconvert
    - asciicheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - godot
    - noctx
    - predeclared
    - whitespace
    - nestif
    - funlen
    # Deprecated linters
    # - wrapcheck
    # - ifshort
    # - varcheck
  disable:
    - deadcode
    - unused
    - dupl
    - depguard
    # https://github.com/golangci/golangci-lint/issues/2649
    - structcheck
    - wastedassign
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - nakedret
        - funlen
        - nestif
        - noctx
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: false
    enable:
      - atomic
      - atomicalign
      - buildtag
      - cgocall
      - composites
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - shift
      - structtag
      - unmarshal
      - unreachable
      - unusedresult
      - tests
      #- fieldalignment
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 18
  goconst:
    min-len: 3
    min-occurrences: 5
  misspell:
    locale: US
    ignore-words: []
  lll:
    line-length: 120
    tab-width: 2
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  dupl:
    threshold: 150
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 90
    statements: 70
