FROM oven/bun:latest

EXPOSE 9091/tcp

COPY resolver/ resolver/
COPY reference_contract/contracts/artifacts/DIDAlgoStorage.arc56.json reference_contract/contracts/artifacts/DIDAlgoStorage.arc56.json

ENTRYPOINT ["bun", "resolver"]
