// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: did/v1/agent_api.proto

package protov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Ticket with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Ticket) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Timestamp

	// no validation rules for NonceValue

	// no validation rules for KeyId

	// no validation rules for Document

	// no validation rules for Proof

	// no validation rules for Signature

	return nil
}

// TicketValidationError is the validation error returned by Ticket.Validate if
// the designated constraints aren't met.
type TicketValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TicketValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TicketValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TicketValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TicketValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TicketValidationError) ErrorName() string { return "TicketValidationError" }

// Error satisfies the builtin error interface
func (e TicketValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTicket.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TicketValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TicketValidationError{}

// Validate checks the field values on AlgoTransaction with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AlgoTransaction) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Amount

	// no validation rules for Note

	// no validation rules for Receiver

	// no validation rules for Sender

	// no validation rules for Fee

	// no validation rules for ConfirmedRound

	return nil
}

// AlgoTransactionValidationError is the validation error returned by
// AlgoTransaction.Validate if the designated constraints aren't met.
type AlgoTransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlgoTransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlgoTransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlgoTransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlgoTransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlgoTransactionValidationError) ErrorName() string { return "AlgoTransactionValidationError" }

// Error satisfies the builtin error interface
func (e AlgoTransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlgoTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlgoTransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlgoTransactionValidationError{}

// Validate checks the field values on PingResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PingResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Ok

	return nil
}

// PingResponseValidationError is the validation error returned by
// PingResponse.Validate if the designated constraints aren't met.
type PingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PingResponseValidationError) ErrorName() string { return "PingResponseValidationError" }

// Error satisfies the builtin error interface
func (e PingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PingResponseValidationError{}

// Validate checks the field values on ProcessRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ProcessRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Task

	if v, ok := interface{}(m.GetTicket()).(interface {
		Validate() error
	}); ok {
		if err := v.Validate(); err != nil {
			return ProcessRequestValidationError{
				field:  "Ticket",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ProcessRequestValidationError is the validation error returned by
// ProcessRequest.Validate if the designated constraints aren't met.
type ProcessRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessRequestValidationError) ErrorName() string { return "ProcessRequestValidationError" }

// Error satisfies the builtin error interface
func (e ProcessRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessRequestValidationError{}

// Validate checks the field values on ProcessResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ProcessResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Ok

	// no validation rules for Identifier

	return nil
}

// ProcessResponseValidationError is the validation error returned by
// ProcessResponse.Validate if the designated constraints aren't met.
type ProcessResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessResponseValidationError) ErrorName() string { return "ProcessResponseValidationError" }

// Error satisfies the builtin error interface
func (e ProcessResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessResponseValidationError{}

// Validate checks the field values on QueryRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *QueryRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Method

	// no validation rules for Subject

	return nil
}

// QueryRequestValidationError is the validation error returned by
// QueryRequest.Validate if the designated constraints aren't met.
type QueryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryRequestValidationError) ErrorName() string { return "QueryRequestValidationError" }

// Error satisfies the builtin error interface
func (e QueryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryRequestValidationError{}

// Validate checks the field values on QueryResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *QueryResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Document

	// no validation rules for Proof

	return nil
}

// QueryResponseValidationError is the validation error returned by
// QueryResponse.Validate if the designated constraints aren't met.
type QueryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryResponseValidationError) ErrorName() string { return "QueryResponseValidationError" }

// Error satisfies the builtin error interface
func (e QueryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryResponseValidationError{}

// Validate checks the field values on AccountInformationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccountInformationRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Protocol

	// no validation rules for Network

	// no validation rules for Address

	return nil
}

// AccountInformationRequestValidationError is the validation error returned by
// AccountInformationRequest.Validate if the designated constraints aren't met.
type AccountInformationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountInformationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountInformationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountInformationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountInformationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountInformationRequestValidationError) ErrorName() string {
	return "AccountInformationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccountInformationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountInformationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountInformationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountInformationRequestValidationError{}

// Validate checks the field values on AccountInformationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccountInformationResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Status

	// no validation rules for Balance

	// no validation rules for PendingRewards

	// no validation rules for TotalRewards

	for idx, item := range m.GetPendingTransactions() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface {
			Validate() error
		}); ok {
			if err := v.Validate(); err != nil {
				return AccountInformationResponseValidationError{
					field:  fmt.Sprintf("PendingTransactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// AccountInformationResponseValidationError is the validation error returned
// by AccountInformationResponse.Validate if the designated constraints aren't met.
type AccountInformationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountInformationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountInformationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountInformationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountInformationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountInformationResponseValidationError) ErrorName() string {
	return "AccountInformationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AccountInformationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountInformationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountInformationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountInformationResponseValidationError{}

// Validate checks the field values on TxParametersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *TxParametersResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Params

	return nil
}

// TxParametersResponseValidationError is the validation error returned by
// TxParametersResponse.Validate if the designated constraints aren't met.
type TxParametersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TxParametersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TxParametersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TxParametersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TxParametersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TxParametersResponseValidationError) ErrorName() string {
	return "TxParametersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TxParametersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTxParametersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TxParametersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TxParametersResponseValidationError{}

// Validate checks the field values on TxSubmitRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *TxSubmitRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Stx

	return nil
}

// TxSubmitRequestValidationError is the validation error returned by
// TxSubmitRequest.Validate if the designated constraints aren't met.
type TxSubmitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TxSubmitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TxSubmitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TxSubmitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TxSubmitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TxSubmitRequestValidationError) ErrorName() string { return "TxSubmitRequestValidationError" }

// Error satisfies the builtin error interface
func (e TxSubmitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTxSubmitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TxSubmitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TxSubmitRequestValidationError{}

// Validate checks the field values on TxSubmitResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *TxSubmitResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// TxSubmitResponseValidationError is the validation error returned by
// TxSubmitResponse.Validate if the designated constraints aren't met.
type TxSubmitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TxSubmitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TxSubmitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TxSubmitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TxSubmitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TxSubmitResponseValidationError) ErrorName() string { return "TxSubmitResponseValidationError" }

// Error satisfies the builtin error interface
func (e TxSubmitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTxSubmitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TxSubmitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TxSubmitResponseValidationError{}

// Validate checks the field values on AccountActivityRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccountActivityRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Protocol

	// no validation rules for Network

	// no validation rules for Address

	return nil
}

// AccountActivityRequestValidationError is the validation error returned by
// AccountActivityRequest.Validate if the designated constraints aren't met.
type AccountActivityRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountActivityRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountActivityRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountActivityRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountActivityRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountActivityRequestValidationError) ErrorName() string {
	return "AccountActivityRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AccountActivityRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountActivityRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountActivityRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountActivityRequestValidationError{}

// Validate checks the field values on AccountActivityResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AccountActivityResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CurrentRound

	// no validation rules for NextToken

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface {
			Validate() error
		}); ok {
			if err := v.Validate(); err != nil {
				return AccountActivityResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// AccountActivityResponseValidationError is the validation error returned by
// AccountActivityResponse.Validate if the designated constraints aren't met.
type AccountActivityResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountActivityResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountActivityResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountActivityResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountActivityResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountActivityResponseValidationError) ErrorName() string {
	return "AccountActivityResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AccountActivityResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountActivityResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountActivityResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountActivityResponseValidationError{}
